name: samtech_analytics
description: Mesures locales minimisées, sans télémétrie distante par défaut.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.2
resolution: workspace

dev_dependencies:
  flutter_lints: ^6.0.0
